---

- name: Gather info about the pod
  become: "{{ podman_rootless | d(true) | bool }}"
  become_user: "{{ podman_user if podman_rootless | d(true) | bool else omit }}"
  containers.podman.podman_pod_info:
    name: "{{ pod_name }}"
  register: _pod_info
  when:
    - pod_name is defined
    - pod_name | length > 0
# - debug: var=_pod_info
# - pause:
- name: Generate systemd unit file for the pod
  become: "{{ podman_rootless | d(true) | bool }}"
  become_user: "{{ podman_user if podman_rootless | d(true) | bool else omit }}"
  containers.podman.podman_generate_systemd:
    name: "{{ pod_name }}"
    dest: "{{ _systemd_service_files_dir }}"
    restart_policy: always
    no_header: true
  register: _pod_generate_systemd_result
  when:
    - pod_name is defined
    - pod_name | length > 0
    - _pod_info.pods | length > 0
- debug: var=_pod_generate_systemd_result
- pause:

- name: Enable systemd service for pod
  become: "{{ podman_rootless | d(true) | bool }}"
  become_user: "{{ podman_user if podman_rootless | d(true) | bool else omit }}"
  environment:
    XDG_RUNTIME_DIR: "{{ _xdg_runtime_dir }}"
  ansible.builtin.systemd:
    name: "{{ 'pod-' + pod_name }}"
    daemon_reload: true
    enabled: true
    scope: "{{ _systemd_scope }}"
  when:
    - pod_name is defined
    - pod_name | length > 0
    - _pod_info.pods | length > 0
