---

# net.core.rmem_max = 2500000

- name: Block to get Podman 5.x on EL9
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == '9'
  block:
    - name: remove package gvisor-tap-vsock
      ansible.builtin.package:
        name: "gvisor-tap-vsock"
        state: absent
    # https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/
    - name: Activate podman copr on EL9 - required to get podman 5.x
      community.general.copr:
        state: disabled
        name: rhcontainerbot/podman-next
        chroot: epel-9-x86_64

- name: Install and update podman  # noqa: package-latest
  ansible.builtin.dnf:
    name: "{{ podman_packages }}"
    enablerepo: "copr:copr.fedorainfracloud.org:rhcontainerbot:podman-next"
    state: latest

- name: Setup bash completion
  ansible.builtin.command: podman completion -f /etc/bash_completion.d/podman bash
  args:
    creates: /etc/bash_completion.d/podman

# - name: Enable podman.sock
#   ansible.builtin.service:
#     name: podman.socket
#     state: started
#     enabled: true
#   tags:
#     - pre_tasks
#     - podman

- name: Create the podman group
  ansible.builtin.group:
    name: "{{ podman_group }}"
    state: present

- name: Create the podman user
  ansible.builtin.user:
    name: "{{ podman_user }}"
    state: present
    group: "{{ podman_group }}"
    home: "{{ podman_user_home }}"
    createhome: true

- name: Add podman user to the podman group
  ansible.builtin.user:
    name: "{{ podman_user }}"
    groups: "{{ podman_group }}"
    append: true

- name: Find uid of user
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.command: "id -u"
  register: _container_run_as_uid
  check_mode: false
  changed_when: false

- name: Set XDG_RUNTIME_DIR in podman user .bashrc
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.lineinfile:
    path: "{{ podman_user_home + '/.bashrc' }}"
    line: "{{ 'export XDG_RUNTIME_DIR=/run/user/' + _container_run_as_uid.stdout }}"

- name: Enable systemd linger mode for podman user
  ansible.builtin.command:
    cmd: loginctl enable-linger {{ podman_user }}
    creates: "{{ '/var/lib/systemd/linger/' + podman_user }}"

- name: Create podman /var/lib/containers equivalent for rootless operations
  ansible.builtin.file:
    path: "{{ podman_user_home + '/.local/share/containers' }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: '0700'
  register: _container_dir

- name: Substitute file contexts for path podman .local/share/containers with /var/lib/containers
  community.general.sefcontext:
    target: "{{ podman_user_home + '/.local/share/containers' }}"
    substitute: /var/lib/containers
    state: present
  register: _container_dir_substitute

- name: Run restore context for .local/share/containers with /var/lib/containers to reload selinux
  ansible.builtin.command:
    cmd: restorecon -F -R -v {{ podman_user_home + '/.local/share/containers' }}
  when:  # noqa: no-handler
    - _container_dir_substitute.changed | bool or _container_dir.changed | bool
    - ansible_selinux and ansible_selinux.status == "enabled"
  register: _result
  changed_when: _result.rc != 0

- name: Create container_storage_dir_base and container_storage_dir_base_local for rootfull container
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ container_storage_dir_base }}"
    - "{{ container_storage_dir_base_local }}"

- name: Create container_storage_dir_base and container_storage_dir_base_local for rootless container
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: '0755'
  loop:
    - "{{ container_storage_dir_base + '/' + podman_user + '/container_data' }}"
    - "{{ container_storage_dir_base_local + '/' + podman_user + '/container_data' }}"

- name: Set selinux policy for podman user home
  community.general.sefcontext:
    target: '{{ item.target }}'
    setype: "{{ item.setype }}"
    reload: true
    state: "{{ item.state }}"
  register: filecontext
  with_items:
    - {target: '{{ podman_user_home }}(/.+)?', setype: 'user_home_dir_t', state: 'present'}
  when: ansible_selinux and ansible_selinux.status == "enabled"

# - ansible.builtin.debug:
#     msg: "{{ filecontext.results[0] }}"

- name: Run restore context to reload selinux
  ansible.builtin.command:
    cmd: restorecon -F -R -v {{ item.target }}
  with_items:
    - {index: 0, target: '{{ podman_user_home }}'}
  when:  # noqa: no-handler
    - filecontext.results[item.index] is changed
    - ansible_selinux and ansible_selinux.status == "enabled"
  register: _result
  changed_when: _result.rc != 0

- name: Create podman systemd unit directory for rootless operations
  ansible.builtin.file:
    path: "{{ podman_user_home + '/.config/systemd/user' }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: '0700'

- name: Create podman configurtation directory for rootless operations
  ansible.builtin.file:
    path: "{{ podman_user_home + '/.config/containers' }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: '0700'

- name: Prepare /etc/containers/containers.conf
  ansible.builtin.copy:
    dest: "{{ item }}"
    mode: "0644"
    force: false
    content: |
      # The containers configuration file specifies all of the available configuration
      # command-line options/flags for container engine tools like Podman & Buildah,
      # but in a TOML format that can be easily modified and versioned.
      #
      # Please refer to containers.conf(5) for details of all configuration options.
      # Not all container engines implement all of the options.
      # All of the options have hard coded defaults and these options will override
      # the built in defaults. Users can then override these options via the command
      # line. Container engines will read containers.conf files in up to three
      # locations in the following order:
      #  1. /usr/share/containers/containers.conf
      #  2. /etc/containers/containers.conf
      #  3. $HOME/.config/containers/containers.conf (Rootless containers ONLY)
      #  Items specified in the latter containers.conf, if they exist, override the
      # previous containers.conf settings, or the default settings.
      #
  loop:
    - "/etc/containers/containers.conf"
    - "{{ podman_user_home + '/.config/containers/containers.conf' }}"

- name: Configure timezone
  community.general.ini_file:
    path: "{{ item }}"
    mode: "0644"
    section: containers
    option: tz
    value: '"local"'
    no_extra_spaces: false
  loop:
    - "/etc/containers/containers.conf"
    - "{{ podman_user_home + '/.config/containers/containers.conf' }}"

# TODO: workaround a current slirp4netns MTU related performance weakness (2023)
- name: Configure podman rootless slirp4netns
  community.general.ini_file:
    path: "{{ podman_user_home + '/.config/containers/containers.conf' }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0644"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
    no_extra_spaces: false
  loop:
    - {section: 'containers', option: 'log_driver', value: '"k8s-file"', state: 'present'}
    - {section: 'engine', option: 'events_logger', value: '"file"', state: 'present'}
    - {section: 'engine', option: 'network_cmd_options', value: '["mtu=20000"]', state: 'present'}

- name: Prepare /etc/containers/storage.conf
  ansible.builtin.copy:
    dest: "{{ item }}"
    mode: "0644"
    force: false
    content: |
      # This file is the configuration file for all tools
      # that use the containers/storage library. The storage.conf file
      # overrides all other storage.conf files. Container engines using the
      # container/storage library do not inherit fields from other storage.conf
      # files.
      #
      #  Note: The storage.conf file overrides other storage.conf files based on this precedence:
      #      /usr/containers/storage.conf
      #      /etc/containers/storage.conf
      #      $HOME/.config/containers/storage.conf
      #      $XDG_CONFIG_HOME/containers/storage.conf (If XDG_CONFIG_HOME is set)
      # See man 5 containers-storage.conf for more information
      # The "container storage" table contains all of the server options.
      #
  loop:
    - "/etc/containers/storage.conf"
    - "{{ podman_user_home + '/.config/containers/storage.conf' }}"

- name: Configure podman storage global
  community.general.ini_file:
    path: /etc/containers/storage.conf
    mode: "0644"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
    no_extra_spaces: false
  loop:
    - {section: 'storage', option: 'driver', value: '"overlay"', state: 'present'}
    - {section: 'storage.options.overlay', option: 'mount_program', value: '"/usr/bin/fuse-overlayfs"', state: 'absent'}
    # - {section: 'storage.options.overlay', option: 'mount_program', value: '"/usr/bin/fuse-overlayfs"',
    #   state: "{{ 'present' if podman_rootless | bool else 'absent' }}"}

- name: Configure podman storage rootless
  community.general.ini_file:
    path: "{{ podman_user_home + '/.config/containers/storage.conf' }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0600"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
    no_extra_spaces: false
  loop:
    - {section: 'storage', option: 'driver', value: '"overlay"', state: 'present'}
    - {section: 'storage.options.overlay', option: 'mount_program', value: '"/usr/bin/fuse-overlayfs"', state: 'absent'}

# looks like subuid and subgid file will be handled automatically
# - name: Set up /etc/subuid for podman user
#   lineinfile:
#     path: /etc/subuid
#     line: "{{ podman_user }}:{{ podman_subuid_range }}"
#     create: true

# - name: Set up /etc/subgid for podman user
#   lineinfile:
#     path: /etc/subgid
#     line: "{{ podman_user }}:{{ podman_subgid_range }}"
#     create: true

- name: Set kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/podman.conf
  loop:
    - {name: "net.core.rmem_max", value: "7500000"}
    - {name: "net.core.wmem_max", value: "7500000"}

- name: Podman network rootful
  containers.podman.podman_network:
    name: "{{ podman_networks.podman_network_root.podman_network_name }}"
    driver: 'bridge'
    internal: false
    # ip_range: "{{ podman_networks.podman_network_root.podman_network_iprange }}"
    subnet: "{{ podman_networks.podman_network_root.podman_network_subnet }}"
    gateway: "{{ podman_networks.podman_network_root.podman_network_gateway }}"
    disable_dns: "{{ podman_networks.podman_network_root.podman_network_disabledns | d(false) }}"
    ipv6: false
    # recreate: true
    state: quadlet
  register: _quadlet_file_status

- name: Start the systemd network unit rootful
  ansible.builtin.systemd_service:
    name: "{{ podman_networks.podman_network_root.podman_network_name ~ '-network' }}"
    daemon_reload: true
    scope: "system"
    state: "started"

- name: Podman network rootless
  become: true
  become_user: "{{ podman_user }}"
  containers.podman.podman_network:
    name: "{{ podman_networks.podman_network_rootless.podman_network_name }}"
    driver: 'bridge'
    internal: false
    # ip_range: "{{ podman_networks.podman_network_rootless.podman_network_iprange }}"
    subnet: "{{ podman_networks.podman_network_rootless.podman_network_subnet }}"
    gateway: "{{ podman_networks.podman_network_rootless.podman_network_gateway }}"
    disable_dns: false
    ipv6: false
    # recreate: true
    state: quadlet
  register: _quadlet_file_status

- name: Start the systemd network unit rootless
  become: true
  become_user: "{{ podman_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ '/run/user/' + _container_run_as_uid.stdout }}"
  ansible.builtin.systemd_service:
    name: "{{ podman_networks.podman_network_rootless.podman_network_name ~ '-network' }}"
    daemon_reload: true
    scope: "user"
    state: "started"
