---

- name: Podman generate systemd become block
  become: "{{ podman_rootless | d(true) | bool }}"
  become_user: "{{ podman_user if podman_rootless | d(true) | bool else omit }}"
  tags:
    - podman_generate_systemd
  block:
    - name: Podman generate systemd | gather info about the pod
      containers.podman.podman_pod_info:
        name: "{{ target }}"
      register: _pod_info
    # - debug: var=_pod_info
    # - pause:

    - name: Podman generate systemd | generate systemd unit file
      containers.podman.podman_generate_systemd:
        name: "{{ target }}"
        dest: "{{ _systemd_service_files_dir }}"
        restart_policy: always
        no_header: true
      register: _podman_generate_systemd_result
    # - debug:
    #     msg: "{{ (_podman_generate_systemd_result.systemd_units | dict2items | list | first).key }}"
    # - pause:

    - name: Podman generate systemd | enable systemd service
      environment:
        XDG_RUNTIME_DIR: "{{ _xdg_runtime_dir }}"
      ansible.builtin.systemd:
        name: "{{ 'pod-' + target if _pod_info.pods | length > 0 else 'container-' + target }}"
        daemon_reload: true
        enabled: true
        scope: "{{ _systemd_scope }}"
        state: started
