---

- name: Include podman_init_vars.yml from sleif.podman
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: sleif.podman/tasks/includes/podman_init_vars.yml
      paths: "{{ lookup('config', 'DEFAULT_ROLES_PATH') }}"

- name: Pod create block
  become: "{{ podman_rootless | d(true) | bool }}"
  become_user: "{{ podman_user if podman_rootless | d(true) | bool else omit }}"
  tags:
    - podman_pod_create
  when:
    - pod_name is defined
    - pod_name | length > 0
  block:
    - name: Pod Create | Gather info about the pod
      containers.podman.podman_pod_info:
        name: "{{ pod_name }}"
      register: _pod_info
    # - debug: var=_pod_info
    # - pause:

    - name: Pod create | Create the pod
      containers.podman.podman_pod:
        name: "{{ pod_name }}"
        publish: "{{ pod_published_ports | default(omit) }}"
        hostname: "{{ pod_name }}"
        # generate_systemd:
        #   path: "{{ _systemd_service_files_dir }}"
        #   restart_policy: always
        network: "{{ podman_network_name }}"
        state: created
      register: _pod_create_result
      when:
        - _pod_info.pods | length == 0
    # - debug: var=_pod_create_result
    # - pause:

    - name: Include tasks from podman_generate_systemd
      ansible.builtin.include_tasks:
        file: podman_generate_systemd.yml
        # apply:
        #   tags:
        #     - podman_generate_systemd
      vars:
        target: "{{ pod_name }}"
      # tags: always
      when:
        - _pod_info.pods | length == 0

    - name: Pod Create | Gather info about the pod
      containers.podman.podman_pod_info:
        name: "{{ pod_name }}"
      register: pod_info_result
